DROP TABLE point_buy_choices IF EXISTS;

CREATE TABLE point_buy_choices (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  str_a TINYINT,
  dex_a TINYINT,
  con_a TINYINT,
  int_a TINYINT,
  wis_a TINYINT,
  cha_a TINYINT
);
