DROP TABLE point_buy_choices IF EXISTS;

CREATE TABLE point_buy_choices (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attr_1 TINYINT,
  attr_2 TINYINT,
  attr_3 TINYINT,
  attr_4 TINYINT,
  attr_5 TINYINT,
  attr_6 TINYINT
);
